### PR TITLE
Poker file

### PR DESCRIPTION
**Pull request by Pulv**
# Description

Poker file created to describe stories and their description and points.

Fixes # None

## File creation

Requires at least one approval prior to merging:

- [ ] Approved By: @RJMathis
- [ ] Approved By: @audricganser
- [ ] Approved By: @FIxBayonets
- [ ] Approved By: @pulv
- [x] Approved By: @travisreed7

### CODE REVIEW

**Comment by travisreed7** [comment]
Would you mind just filling out the pull request template real quick? (Description and type of change)

**Comment by travisreed7** [comment]
I noticed on some it has x days for actual. Do you think we should update and fill those out?

**Comment by Pulv** [comment]
x is for not having it done yet, unless I am confused. Please update it as necessary.

**Comment by travisreed7** [comment]
Looks good. Approved 👍

**Pull request merged**
